In [70]:
from yahooquery import Ticker
import pandas as pd
from datetime import datetime

def get_raw_yahooquery(symbol_list, start_date, import_time):
    try:
        # Attempt to fetch data from Yahoo Finance
        data = Ticker(symbol_list)
        
        # Fetch historical data
        hist_data = data.history(start=start_date, end="2025-01-08", interval="1d")
        
        # Reshape the data to include a 'Ticker' column
        hist_data.reset_index(inplace=True)  # Reset index to make Ticker and Date columns
        
        # Select only required columns
        columns_to_select = ["date", "symbol", "open", "high", "low", "close", "volume"]
        hist_data = hist_data[columns_to_select]
        
        # Add a new field for the current datetime
        hist_data["import_time"] = datetime.now()

        # Return the processed data
        return hist_data
    
    except Exception as e:
        # Handle any exception that occurred during the execution
        print(f"An error occurred: {e}")
        
        # Return an empty DataFrame with the same columns as the expected result
        return pd.DataFrame(columns=["date", "symbol", "open", "high", "low", "close", "volume", "import_time"])
    
    finally:
        # Code in the finally block will execute no matter what
        print("Execution completed, regardless of success or failure.")

In [71]:
# symbol_list=['C', 'AAPL']
# get_raw_yahooquery(symbol_list, '2025-1-1', datetime.now())

Execution completed, regardless of success or failure.

,date,symbol,open,high,low,close,volume,import_time
0,2025-01-02,C,70.940002,71.160004,69.650002,69.940002,9827400,2025-01-09 04:25:15.936245
1,2025-01-03,C,70.879997,71.089996,69.849998,71.000000,11342900,2025-01-09 04:25:15.936245
2,2025-01-06,C,72.230003,73.989998,71.879997,72.739998,19199700,2025-01-09 04:25:15.936245
3,2025-01-07,C,73.900002,74.290001,72.739998,73.680000,18309400,2025-01-09 04:25:15.936245
4,2025-01-02,AAPL,248.929993,249.100006,241.820007,243.850006,55740700,2025-01-09 04:25:15.936245
5,2025-01-03,AAPL,243.360001,244.179993,241.889999,243.360001,40244100,2025-01-09 04:25:15.936245
6,2025-01-06,AAPL,244.309998,247.330002,243.199997,245.000000,45045600,2025-01-09 04:25:15.936245
7,2025-01-07,AAPL,242.979996,245.550003,241.350006,242.210007,40856000,2025-01-09 04:25:15.936245